config/routes.rb
Rails.application.routes.draw do
 resources :textos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/texto.rb
class Texto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/textos_controller.rb
class TextosController < ApplicationController
  before_action :find_texto, only: [:show, :edit, :update, :destroy]

  def index #disponibiliza de forma geral todos os textos publicados
  end

  def new
    @texto = Texto.new #cria uma nova materia no nosso formulario
  end

  def create
    @texto = Texto.new texto_params

    if @texto.save # se a matéria for salva essas serão as mensagens que aparecerão no browser
      redirect_to @texto, notice: "Pronto! Sua matéria foi ao ar!"
    else
      render 'new', notice: "ihhhh, não é seu dia de sorte..."
    end
  end

  def show #mostra com mais detalhes os textos
  end

  def edit
  end

  def update
    if @texto.update texto_params #se o texto foi atualizado, a pagina sera renderizada para o texto atualizado
      redirect_to @texto, notice: "Sua matéria foi salva!"
    else
      render 'edit' #caso encontre algum erro, a pagina renderizará para a pagina de edição
    end
  end

  def destroy
    @texto.destroy
    redirect_to textos_path
  end

  private

  def texto_params #ele permite os atributos que foram estabelecidos no model
    params.require(:texto).permit(:titulo, :conteudo)
  end

  def find_texto
    @texto = Texto.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/textos_helper.rb
module TextosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrabalhoRani</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer id="main_footer">
  <p class="copyright"> Feito com amor por Letícia Vaneli</p>
    <nav>
      <a href="https://www.twitter.com/leticiavaneli" target="_blank"><i class="fa fa-twitter"></i></a>
      <a href="https://www.instagram.com/petite.epiphanie" target="_blank"><i class="fa fa-instagram"></i></a>
      <a href="https://www.facebook.com/leticia.vanelli" target="_blank"><i class="fa fa-facebook"></i></a>
      <a href="https://www.linkedin.com/in/leticiarafael/" target="_blank"><i class="fa fa-linkedin"></i></a>
  </nav>
</footer>

app/views/shared/_form.html.erb
<%= form_for @texto do |f| %>
  <% if @texto.errors.any? %>
    <h2><%= pluralize(@texto.errors.count, "error") %> previna que esse texto salve: </h2>
    <ul>
      <% @texto.errors.full_messages.each do |msg|%>
        <li><%= msg %></li>
      <% end %>
    <ul>
  <% end %>

  <%= f.label :titulo, "Escreva seu título aqui!" %><br>
  <%= f.text_field :titulo%>

  <br>
  <br>

  <%= f.label :conteudo, "Agora a escreva sua matéria!" %><br>
  <%= f.text_area :conteudo%>

  <br>
  <br>

  <%= f.submit%>

<%end%>

app/views/shared/_header.html.erb
<header id="main_navigation" class="clearfix">

</header>

app/views/textos/edit.html.erb
<h1>Edite sua matéria</h1>

<%= render 'shared/form' %>

app/views/textos/index.html.erb
<h1>eai garotada!</h1>

app/views/textos/new.html.erb
<h1>Tem matéria nova?</h1>

<%= render 'shared/form' %>

app/views/textos/show.html.erb
<div id="texto_show_conteudo" class="skinny_wrapper wrapper_padding">
  <header>
    <h2><%= @texto.titulo %></h2>
    <hr>
  </header>

  <div id="conteudo">
    <h1><%= @texto.conteudo %></h1>
  </div>

  <%= link_to "Edite", edit_texto_path(@texto) %>
  <%= link_to "Delete", texto_path(@texto), method: :delete, data: { confirm: "Tem certeza que você quer deletar essa matéria?"} %>

  <hr>
  <hr>